; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.34"

; Modules
projects[administerusersbyrole][version] = "1.0-beta1"

projects[block_revisions][version] = "1.0+0-dev"

projects[ctools][version] = "1.5"

projects[calendar][version] = "3.5"

projects[ckeditor][version] = "1.16"

projects[ckeditor_link][version] = "2.3"

projects[colorbox][version] = "2.8"

projects[content_type_extras][version] = "1.8"

projects[date][version] = "2.8"

projects[devel][version] = "1.5"

projects[diff][version] = "3.2"

projects[ds][version] = "2.7"

projects[entity][version] = "1.5"

projects[extlink][version] = "1.18"

projects[extlink_extra][version] = "1.0-rc2"

projects[features][version] = "2.2"

projects[find_content][version] = "1.4"

projects[form_builder][version] = "1.6"

projects[panels][version] = "3.4"

projects[imce][version] = "1.9"

projects[jquery_update][version] = "2.4"

projects[libraries][version] = "2.2"

projects[masquerade][version] = "1.0-rc7"

projects[metatags_quick][version] = "2.9"

projects[migrate][version] = "2.5"

projects[module_filter][version] = "2.0-alpha2"

projects[navbar][version] = "1.4"

projects[node_convert][version] = "1.2"

projects[nodeblock][version] = "1.6"

projects[options_element][version] = "1.12"

projects[owlcarousel][version] = "1.2"

projects[pagepreview][version] = "1.x-dev"

projects[pathauto][version] = "1.2"

projects[redirect][version] = "1.0-rc1"

projects[responsive_preview][version] = "1.1"

projects[revisioning][version] = "1.9"

projects[scheduler][version] = "1.3"

projects[site_map][version] = "1.2"

projects[smtp][version] = "1.0"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.5"

projects[user_create_by_role][version] = "1.01"

projects[variable][version] = "2.5"

projects[views][version] = "3.8"

projects[webform][version] = "4.1"

projects[workbench][version] = "1.2"

; Themes
projects[ember][version] = "2.0-alpha2+33-dev"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[Modernizr-2.7.1][download][type] = ""
libraries[Modernizr-2.7.1][download][url] = ""
libraries[Modernizr-2.7.1][directory_name] = "Modernizr-2.7.1"
libraries[Modernizr-2.7.1][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

